//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USRaceList.PoolInfoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToteLinkRequest", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(USRaceList.PoolInfoService.TotalsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(USRaceList.PoolInfoService.WillpaysRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(USRaceList.PoolInfoService.MatrixRequest))]
    public partial class ToteLinkRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private USRaceList.PoolInfoService.Source SourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public USRaceList.PoolInfoService.Source Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Source", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Common")]
    [System.SerializableAttribute()]
    public partial struct Source : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SystemIdField;
        
        private string SourceIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SystemId {
            get {
                return this.SystemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemIdField, value) != true)) {
                    this.SystemIdField = value;
                    this.RaisePropertyChanged("SystemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string SourceId {
            get {
                return this.SourceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIdField, value) != true)) {
                    this.SourceIdField = value;
                    this.RaisePropertyChanged("SourceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TotalsRequest", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo")]
    [System.SerializableAttribute()]
    public partial class TotalsRequest : USRaceList.PoolInfoService.ToteLinkRequest {
        
        private string EventIdField;
        
        private int RaceIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EventIdField, value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RaceId {
            get {
                return this.RaceIdField;
            }
            set {
                if ((this.RaceIdField.Equals(value) != true)) {
                    this.RaceIdField = value;
                    this.RaisePropertyChanged("RaceId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WillpaysRequest", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo")]
    [System.SerializableAttribute()]
    public partial class WillpaysRequest : USRaceList.PoolInfoService.ToteLinkRequest {
        
        private string EventIdField;
        
        private int RaceIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EventIdField, value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RaceId {
            get {
                return this.RaceIdField;
            }
            set {
                if ((this.RaceIdField.Equals(value) != true)) {
                    this.RaceIdField = value;
                    this.RaisePropertyChanged("RaceId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatrixRequest", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo")]
    [System.SerializableAttribute()]
    public partial class MatrixRequest : USRaceList.PoolInfoService.ToteLinkRequest {
        
        private string EventIdField;
        
        private int RaceIdField;
        
        private string PoolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<USRaceList.PoolInfoService.MatrixFormat> MatrixFormatField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EventIdField, value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RaceId {
            get {
                return this.RaceIdField;
            }
            set {
                if ((this.RaceIdField.Equals(value) != true)) {
                    this.RaceIdField = value;
                    this.RaisePropertyChanged("RaceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string PoolId {
            get {
                return this.PoolIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PoolIdField, value) != true)) {
                    this.PoolIdField = value;
                    this.RaisePropertyChanged("PoolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Nullable<USRaceList.PoolInfoService.MatrixFormat> MatrixFormat {
            get {
                return this.MatrixFormatField;
            }
            set {
                if ((this.MatrixFormatField.Equals(value) != true)) {
                    this.MatrixFormatField = value;
                    this.RaisePropertyChanged("MatrixFormat");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatrixFormat", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo")]
    public enum MatrixFormat : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Odds = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Prices = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Morning = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pool = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToteLinkResponse", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(USRaceList.PoolInfoService.TotalsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(USRaceList.PoolInfoService.WillpaysResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(USRaceList.PoolInfoService.MatrixResponse))]
    public partial class ToteLinkResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RunIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.PoolInfoService.Source SourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RunId {
            get {
                return this.RunIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RunIdField, value) != true)) {
                    this.RunIdField = value;
                    this.RaisePropertyChanged("RunId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupIdField, value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public USRaceList.PoolInfoService.Source Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TotalsResponse", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo")]
    [System.SerializableAttribute()]
    public partial class TotalsResponse : USRaceList.PoolInfoService.ToteLinkResponse {
        
        private string EventIdField;
        
        private int RaceIdField;
        
        private string CurrencyIdField;
        
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.PoolInfoService.PoolTotals PoolTotalsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EventIdField, value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RaceId {
            get {
                return this.RaceIdField;
            }
            set {
                if ((this.RaceIdField.Equals(value) != true)) {
                    this.RaceIdField = value;
                    this.RaisePropertyChanged("RaceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string CurrencyId {
            get {
                return this.CurrencyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyIdField, value) != true)) {
                    this.CurrencyIdField = value;
                    this.RaisePropertyChanged("CurrencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public USRaceList.PoolInfoService.PoolTotals PoolTotals {
            get {
                return this.PoolTotalsField;
            }
            set {
                if ((object.ReferenceEquals(this.PoolTotalsField, value) != true)) {
                    this.PoolTotalsField = value;
                    this.RaisePropertyChanged("PoolTotals");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WillpaysResponse", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo")]
    [System.SerializableAttribute()]
    public partial class WillpaysResponse : USRaceList.PoolInfoService.ToteLinkResponse {
        
        private string EventIdField;
        
        private int RaceIdField;
        
        private string CurrencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WillpayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.PoolInfoService.Pools PoolsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EventIdField, value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RaceId {
            get {
                return this.RaceIdField;
            }
            set {
                if ((this.RaceIdField.Equals(value) != true)) {
                    this.RaceIdField = value;
                    this.RaisePropertyChanged("RaceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string CurrencyId {
            get {
                return this.CurrencyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyIdField, value) != true)) {
                    this.CurrencyIdField = value;
                    this.RaisePropertyChanged("CurrencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string WillpayName {
            get {
                return this.WillpayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WillpayNameField, value) != true)) {
                    this.WillpayNameField = value;
                    this.RaisePropertyChanged("WillpayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public USRaceList.PoolInfoService.Pools Pools {
            get {
                return this.PoolsField;
            }
            set {
                if ((object.ReferenceEquals(this.PoolsField, value) != true)) {
                    this.PoolsField = value;
                    this.RaisePropertyChanged("Pools");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatrixResponse", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo")]
    [System.SerializableAttribute()]
    public partial class MatrixResponse : USRaceList.PoolInfoService.ToteLinkResponse {
        
        private string EventIdField;
        
        private int RaceIdField;
        
        private string PoolIdField;
        
        private string CurrencyIdField;
        
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoolNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MorningLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SymmetricField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceBaseWagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfRowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.PoolInfoService.Rows RowsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EventIdField, value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RaceId {
            get {
                return this.RaceIdField;
            }
            set {
                if ((this.RaceIdField.Equals(value) != true)) {
                    this.RaceIdField = value;
                    this.RaisePropertyChanged("RaceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string PoolId {
            get {
                return this.PoolIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PoolIdField, value) != true)) {
                    this.PoolIdField = value;
                    this.RaisePropertyChanged("PoolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string CurrencyId {
            get {
                return this.CurrencyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyIdField, value) != true)) {
                    this.CurrencyIdField = value;
                    this.RaisePropertyChanged("CurrencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PoolName {
            get {
                return this.PoolNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PoolNameField, value) != true)) {
                    this.PoolNameField = value;
                    this.RaisePropertyChanged("PoolName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public bool MorningLine {
            get {
                return this.MorningLineField;
            }
            set {
                if ((this.MorningLineField.Equals(value) != true)) {
                    this.MorningLineField = value;
                    this.RaisePropertyChanged("MorningLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public bool Final {
            get {
                return this.FinalField;
            }
            set {
                if ((this.FinalField.Equals(value) != true)) {
                    this.FinalField = value;
                    this.RaisePropertyChanged("Final");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public bool Symmetric {
            get {
                return this.SymmetricField;
            }
            set {
                if ((this.SymmetricField.Equals(value) != true)) {
                    this.SymmetricField = value;
                    this.RaisePropertyChanged("Symmetric");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public System.Nullable<decimal> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public System.Nullable<decimal> PriceBaseWager {
            get {
                return this.PriceBaseWagerField;
            }
            set {
                if ((this.PriceBaseWagerField.Equals(value) != true)) {
                    this.PriceBaseWagerField = value;
                    this.RaisePropertyChanged("PriceBaseWager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public int NumberOfRows {
            get {
                return this.NumberOfRowsField;
            }
            set {
                if ((this.NumberOfRowsField.Equals(value) != true)) {
                    this.NumberOfRowsField = value;
                    this.RaisePropertyChanged("NumberOfRows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public int NumberOfColumns {
            get {
                return this.NumberOfColumnsField;
            }
            set {
                if ((this.NumberOfColumnsField.Equals(value) != true)) {
                    this.NumberOfColumnsField = value;
                    this.RaisePropertyChanged("NumberOfColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public USRaceList.PoolInfoService.Rows Rows {
            get {
                return this.RowsField;
            }
            set {
                if ((object.ReferenceEquals(this.RowsField, value) != true)) {
                    this.RowsField = value;
                    this.RaisePropertyChanged("Rows");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Rows", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo", ItemName="Row")]
    [System.SerializableAttribute()]
    public class Rows : System.Collections.Generic.List<USRaceList.PoolInfoService.Row> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PoolTotals", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo", ItemName="PoolTotal")]
    [System.SerializableAttribute()]
    public class PoolTotals : System.Collections.Generic.List<USRaceList.PoolInfoService.PoolTotal> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PoolTotal", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo")]
    [System.SerializableAttribute()]
    public partial class PoolTotal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PoolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoolNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> HandleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PoolId {
            get {
                return this.PoolIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PoolIdField, value) != true)) {
                    this.PoolIdField = value;
                    this.RaisePropertyChanged("PoolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PoolName {
            get {
                return this.PoolNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PoolNameField, value) != true)) {
                    this.PoolNameField = value;
                    this.RaisePropertyChanged("PoolName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public bool Final {
            get {
                return this.FinalField;
            }
            set {
                if ((this.FinalField.Equals(value) != true)) {
                    this.FinalField = value;
                    this.RaisePropertyChanged("Final");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Nullable<decimal> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Nullable<decimal> Handle {
            get {
                return this.HandleField;
            }
            set {
                if ((this.HandleField.Equals(value) != true)) {
                    this.HandleField = value;
                    this.RaisePropertyChanged("Handle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Nullable<decimal> Net {
            get {
                return this.NetField;
            }
            set {
                if ((this.NetField.Equals(value) != true)) {
                    this.NetField = value;
                    this.RaisePropertyChanged("Net");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Pools", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo", ItemName="PoolWillpays")]
    [System.SerializableAttribute()]
    public class Pools : System.Collections.Generic.List<USRaceList.PoolInfoService.PoolWillpays> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PoolWillpays", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo")]
    [System.SerializableAttribute()]
    public partial class PoolWillpays : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PoolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoolNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RaceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.PoolInfoService.Willpays WillpaysField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PoolId {
            get {
                return this.PoolIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PoolIdField, value) != true)) {
                    this.PoolIdField = value;
                    this.RaisePropertyChanged("PoolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PoolName {
            get {
                return this.PoolNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PoolNameField, value) != true)) {
                    this.PoolNameField = value;
                    this.RaisePropertyChanged("PoolName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<decimal> Live {
            get {
                return this.LiveField;
            }
            set {
                if ((this.LiveField.Equals(value) != true)) {
                    this.LiveField = value;
                    this.RaisePropertyChanged("Live");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public int RaceId {
            get {
                return this.RaceIdField;
            }
            set {
                if ((this.RaceIdField.Equals(value) != true)) {
                    this.RaceIdField = value;
                    this.RaisePropertyChanged("RaceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Nullable<decimal> Wager {
            get {
                return this.WagerField;
            }
            set {
                if ((this.WagerField.Equals(value) != true)) {
                    this.WagerField = value;
                    this.RaisePropertyChanged("Wager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public USRaceList.PoolInfoService.Willpays Willpays {
            get {
                return this.WillpaysField;
            }
            set {
                if ((object.ReferenceEquals(this.WillpaysField, value) != true)) {
                    this.WillpaysField = value;
                    this.RaisePropertyChanged("Willpays");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Willpays", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo", ItemName="Willpay")]
    [System.SerializableAttribute()]
    public class Willpays : System.Collections.Generic.List<USRaceList.PoolInfoService.Willpay> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Willpay", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo")]
    [System.SerializableAttribute()]
    public partial class Willpay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.PoolInfoService.Pays PaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinishField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public USRaceList.PoolInfoService.Pays Pays {
            get {
                return this.PaysField;
            }
            set {
                if ((object.ReferenceEquals(this.PaysField, value) != true)) {
                    this.PaysField = value;
                    this.RaisePropertyChanged("Pays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Finish {
            get {
                return this.FinishField;
            }
            set {
                if ((object.ReferenceEquals(this.FinishField, value) != true)) {
                    this.FinishField = value;
                    this.RaisePropertyChanged("Finish");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Pays", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo", ItemName="Pay")]
    [System.SerializableAttribute()]
    public class Pays : System.Collections.Generic.List<USRaceList.PoolInfoService.Pay> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pay", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo")]
    [System.SerializableAttribute()]
    public partial class Pay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RunnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ScratchedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NoMoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormattedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RunnerId {
            get {
                return this.RunnerIdField;
            }
            set {
                if ((this.RunnerIdField.Equals(value) != true)) {
                    this.RunnerIdField = value;
                    this.RaisePropertyChanged("RunnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public int Required {
            get {
                return this.RequiredField;
            }
            set {
                if ((this.RequiredField.Equals(value) != true)) {
                    this.RequiredField = value;
                    this.RaisePropertyChanged("Required");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public bool Scratched {
            get {
                return this.ScratchedField;
            }
            set {
                if ((this.ScratchedField.Equals(value) != true)) {
                    this.ScratchedField = value;
                    this.RaisePropertyChanged("Scratched");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public bool NoMoney {
            get {
                return this.NoMoneyField;
            }
            set {
                if ((this.NoMoneyField.Equals(value) != true)) {
                    this.NoMoneyField = value;
                    this.RaisePropertyChanged("NoMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Formatted {
            get {
                return this.FormattedField;
            }
            set {
                if ((object.ReferenceEquals(this.FormattedField, value) != true)) {
                    this.FormattedField = value;
                    this.RaisePropertyChanged("Formatted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Row", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo")]
    [System.SerializableAttribute()]
    public partial class Row : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.PoolInfoService.Columns ColumnsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RowNumber {
            get {
                return this.RowNumberField;
            }
            set {
                if ((this.RowNumberField.Equals(value) != true)) {
                    this.RowNumberField = value;
                    this.RaisePropertyChanged("RowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public USRaceList.PoolInfoService.Columns Columns {
            get {
                return this.ColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnsField, value) != true)) {
                    this.ColumnsField = value;
                    this.RaisePropertyChanged("Columns");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Columns", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo", ItemName="Column")]
    [System.SerializableAttribute()]
    public class Columns : System.Collections.Generic.List<USRaceList.PoolInfoService.Column> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Column", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo")]
    [System.SerializableAttribute()]
    public partial class Column : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ColumnNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InvalidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ScratchedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.PoolInfoService.ChangeDirection DirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormattedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ColumnNumber {
            get {
                return this.ColumnNumberField;
            }
            set {
                if ((this.ColumnNumberField.Equals(value) != true)) {
                    this.ColumnNumberField = value;
                    this.RaisePropertyChanged("ColumnNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Invalid {
            get {
                return this.InvalidField;
            }
            set {
                if ((this.InvalidField.Equals(value) != true)) {
                    this.InvalidField = value;
                    this.RaisePropertyChanged("Invalid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Scratched {
            get {
                return this.ScratchedField;
            }
            set {
                if ((this.ScratchedField.Equals(value) != true)) {
                    this.ScratchedField = value;
                    this.RaisePropertyChanged("Scratched");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public USRaceList.PoolInfoService.ChangeDirection Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((this.DirectionField.Equals(value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Nullable<decimal> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Formatted {
            get {
                return this.FormattedField;
            }
            set {
                if ((object.ReferenceEquals(this.FormattedField, value) != true)) {
                    this.FormattedField = value;
                    this.RaisePropertyChanged("Formatted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeDirection", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo")]
    public enum ChangeDirection : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoChange = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Up = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Down = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToteLinkFault", Namespace="http://schema.unitedtote.com/ToteLink/Faults/2008/10")]
    [System.SerializableAttribute()]
    public partial class ToteLinkFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
    [System.SerializableAttribute()]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.PoolInfoService.ValidationDetail[] DetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public USRaceList.PoolInfoService.ValidationDetail[] Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationDetail", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Practices.EnterpriseLibrary.Val" +
        "idation.Integration.WCF")]
    [System.SerializableAttribute()]
    public partial class ValidationDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag {
            get {
                return this.TagField;
            }
            set {
                if ((object.ReferenceEquals(this.TagField, value) != true)) {
                    this.TagField = value;
                    this.RaisePropertyChanged("Tag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo", ConfigurationName="PoolInfoService.PoolInfo")]
    public interface PoolInfo {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schema.unitedtote.com/ToteLink/2008/06/Common) of message KeepaliveRequest does not match the default value (http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo)
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.unitedtote.com/ToteLink/2008/06/Common/Keepalive/Keepalive", ReplyAction="http://schema.unitedtote.com/ToteLink/2008/06/Common/Keepalive/KeepaliveResponse")]
        USRaceList.PoolInfoService.KeepaliveResponse Keepalive(USRaceList.PoolInfoService.KeepaliveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo/PoolInfo/GetMatrix", ReplyAction="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo/PoolInfo/GetMatrixResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(USRaceList.PoolInfoService.ToteLinkFault), Action="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo/PoolInfo/GetMatrixToteFaul" +
            "tFault", Name="ToteLinkFault", Namespace="http://schema.unitedtote.com/ToteLink/Faults/2008/10")]
        [System.ServiceModel.FaultContractAttribute(typeof(USRaceList.PoolInfoService.ValidationFault), Action="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo/PoolInfo/GetMatrixValidati" +
            "onFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="MatrixResponse")]
        USRaceList.PoolInfoService.MatrixResponse GetMatrix(USRaceList.PoolInfoService.MatrixRequest MatrixRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo/PoolInfo/GetPoolTotals", ReplyAction="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo/PoolInfo/GetPoolTotalsResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(USRaceList.PoolInfoService.ToteLinkFault), Action="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo/PoolInfo/GetPoolTotalsTote" +
            "FaultFault", Name="ToteLinkFault", Namespace="http://schema.unitedtote.com/ToteLink/Faults/2008/10")]
        [System.ServiceModel.FaultContractAttribute(typeof(USRaceList.PoolInfoService.ValidationFault), Action="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo/PoolInfo/GetPoolTotalsVali" +
            "dationFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="TotalsResponse")]
        USRaceList.PoolInfoService.TotalsResponse GetPoolTotals(USRaceList.PoolInfoService.TotalsRequest TotalsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo/PoolInfo/GetWillpays", ReplyAction="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo/PoolInfo/GetWillpaysRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(USRaceList.PoolInfoService.ValidationFault), Action="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo/PoolInfo/GetWillpaysValida" +
            "tionFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
        [System.ServiceModel.FaultContractAttribute(typeof(USRaceList.PoolInfoService.ToteLinkFault), Action="http://schema.unitedtote.com/ToteLink/2008/06/PoolInfo/PoolInfo/GetWillpaysToteFa" +
            "ultFault", Name="ToteLinkFault", Namespace="http://schema.unitedtote.com/ToteLink/Faults/2008/10")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="WillpaysResponse")]
        USRaceList.PoolInfoService.WillpaysResponse GetWillpays(USRaceList.PoolInfoService.WillpaysRequest WillpaysRequest);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Keepalive", WrapperNamespace="http://schema.unitedtote.com/ToteLink/2008/06/Common", IsWrapped=true)]
    public partial class KeepaliveRequest {
        
        public KeepaliveRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KeepaliveResponse", WrapperNamespace="http://schema.unitedtote.com/ToteLink/2008/06/Common", IsWrapped=true)]
    public partial class KeepaliveResponse {
        
        public KeepaliveResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PoolInfoChannel : USRaceList.PoolInfoService.PoolInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PoolInfoClient : System.ServiceModel.ClientBase<USRaceList.PoolInfoService.PoolInfo>, USRaceList.PoolInfoService.PoolInfo {
        
        public PoolInfoClient() {
        }
        
        public PoolInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PoolInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PoolInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PoolInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USRaceList.PoolInfoService.KeepaliveResponse USRaceList.PoolInfoService.PoolInfo.Keepalive(USRaceList.PoolInfoService.KeepaliveRequest request) {
            return base.Channel.Keepalive(request);
        }
        
        public void Keepalive() {
            USRaceList.PoolInfoService.KeepaliveRequest inValue = new USRaceList.PoolInfoService.KeepaliveRequest();
            USRaceList.PoolInfoService.KeepaliveResponse retVal = ((USRaceList.PoolInfoService.PoolInfo)(this)).Keepalive(inValue);
        }
        
        public USRaceList.PoolInfoService.MatrixResponse GetMatrix(USRaceList.PoolInfoService.MatrixRequest MatrixRequest) {
            return base.Channel.GetMatrix(MatrixRequest);
        }
        
        public USRaceList.PoolInfoService.TotalsResponse GetPoolTotals(USRaceList.PoolInfoService.TotalsRequest TotalsRequest) {
            return base.Channel.GetPoolTotals(TotalsRequest);
        }
        
        public USRaceList.PoolInfoService.WillpaysResponse GetWillpays(USRaceList.PoolInfoService.WillpaysRequest WillpaysRequest) {
            return base.Channel.GetWillpays(WillpaysRequest);
        }
    }
}
