//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USRaceList.ConfigurationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToteLinkRequest", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(USRaceList.ConfigurationService.ConfigurationRequest))]
    public partial class ToteLinkRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private USRaceList.ConfigurationService.Source SourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public USRaceList.ConfigurationService.Source Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Source", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Common")]
    [System.SerializableAttribute()]
    public partial struct Source : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SystemIdField;
        
        private string SourceIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SystemId {
            get {
                return this.SystemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemIdField, value) != true)) {
                    this.SystemIdField = value;
                    this.RaisePropertyChanged("SystemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string SourceId {
            get {
                return this.SourceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIdField, value) != true)) {
                    this.SourceIdField = value;
                    this.RaisePropertyChanged("SourceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigurationRequest", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration")]
    [System.SerializableAttribute()]
    public partial class ConfigurationRequest : USRaceList.ConfigurationService.ToteLinkRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToteLinkResponse", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(USRaceList.ConfigurationService.ConfigurationResponse))]
    public partial class ToteLinkResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RunIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.Error ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.Source SourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RunId {
            get {
                return this.RunIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RunIdField, value) != true)) {
                    this.RunIdField = value;
                    this.RaisePropertyChanged("RunId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupIdField, value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public USRaceList.ConfigurationService.Error Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public USRaceList.ConfigurationService.Source Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Common")]
    [System.SerializableAttribute()]
    public partial struct Error : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ParamsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] Params {
            get {
                return this.ParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamsField, value) != true)) {
                    this.ParamsField = value;
                    this.RaisePropertyChanged("Params");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigurationResponse", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration")]
    [System.SerializableAttribute()]
    public partial class ConfigurationResponse : USRaceList.ConfigurationService.ToteLinkResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToteVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.Currencies CurrenciesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.ConfigurationAccount AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.ConfigurationDemand DemandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.ConfigurationContest ContestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeZoneIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.Advertisement AdvertisementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AssistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CancelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountTimeoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.Limits LimitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RedactField;
        
        private string ToteLinkVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<USRaceList.ConfigurationService.SourceMode> ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MixedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FunBetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ManualLogOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ParlayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VideoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FundedTimeoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UnfundedTimeoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CashReceiptsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TransactionReceiptsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.Channels ChannelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.Languages LanguagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BAMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PatronOffsetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PatronSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AccountOffsetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AccountSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FractionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AccountCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InquiryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ScrambleKeyPadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SwipeRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool QuickField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CurrentTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DateFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatePictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BrandTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LongTicketField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ToteVersion {
            get {
                return this.ToteVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.ToteVersionField, value) != true)) {
                    this.ToteVersionField = value;
                    this.RaisePropertyChanged("ToteVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public USRaceList.ConfigurationService.Currencies Currencies {
            get {
                return this.CurrenciesField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrenciesField, value) != true)) {
                    this.CurrenciesField = value;
                    this.RaisePropertyChanged("Currencies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public USRaceList.ConfigurationService.ConfigurationAccount Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public USRaceList.ConfigurationService.ConfigurationDemand Demand {
            get {
                return this.DemandField;
            }
            set {
                if ((object.ReferenceEquals(this.DemandField, value) != true)) {
                    this.DemandField = value;
                    this.RaisePropertyChanged("Demand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public USRaceList.ConfigurationService.ConfigurationContest Contest {
            get {
                return this.ContestField;
            }
            set {
                if ((object.ReferenceEquals(this.ContestField, value) != true)) {
                    this.ContestField = value;
                    this.RaisePropertyChanged("Contest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TimeZoneIndex {
            get {
                return this.TimeZoneIndexField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeZoneIndexField, value) != true)) {
                    this.TimeZoneIndexField = value;
                    this.RaisePropertyChanged("TimeZoneIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CustomerLogo {
            get {
                return this.CustomerLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerLogoField, value) != true)) {
                    this.CustomerLogoField = value;
                    this.RaisePropertyChanged("CustomerLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public USRaceList.ConfigurationService.Advertisement Advertisement {
            get {
                return this.AdvertisementField;
            }
            set {
                if ((object.ReferenceEquals(this.AdvertisementField, value) != true)) {
                    this.AdvertisementField = value;
                    this.RaisePropertyChanged("Advertisement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public bool Assistance {
            get {
                return this.AssistanceField;
            }
            set {
                if ((this.AssistanceField.Equals(value) != true)) {
                    this.AssistanceField = value;
                    this.RaisePropertyChanged("Assistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public bool Cancels {
            get {
                return this.CancelsField;
            }
            set {
                if ((this.CancelsField.Equals(value) != true)) {
                    this.CancelsField = value;
                    this.RaisePropertyChanged("Cancels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public int AccountTimeout {
            get {
                return this.AccountTimeoutField;
            }
            set {
                if ((this.AccountTimeoutField.Equals(value) != true)) {
                    this.AccountTimeoutField = value;
                    this.RaisePropertyChanged("AccountTimeout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public USRaceList.ConfigurationService.Limits Limits {
            get {
                return this.LimitsField;
            }
            set {
                if ((this.LimitsField.Equals(value) != true)) {
                    this.LimitsField = value;
                    this.RaisePropertyChanged("Limits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public System.Nullable<int> Redact {
            get {
                return this.RedactField;
            }
            set {
                if ((this.RedactField.Equals(value) != true)) {
                    this.RedactField = value;
                    this.RaisePropertyChanged("Redact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public string ToteLinkVersion {
            get {
                return this.ToteLinkVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.ToteLinkVersionField, value) != true)) {
                    this.ToteLinkVersionField = value;
                    this.RaisePropertyChanged("ToteLinkVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string DefaultEvent {
            get {
                return this.DefaultEventField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultEventField, value) != true)) {
                    this.DefaultEventField = value;
                    this.RaisePropertyChanged("DefaultEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string TicketLogo {
            get {
                return this.TicketLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketLogoField, value) != true)) {
                    this.TicketLogoField = value;
                    this.RaisePropertyChanged("TicketLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Terminal {
            get {
                return this.TerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalField, value) != true)) {
                    this.TerminalField = value;
                    this.RaisePropertyChanged("Terminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public System.Nullable<USRaceList.ConfigurationService.SourceMode> Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((this.ModeField.Equals(value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public bool Mixed {
            get {
                return this.MixedField;
            }
            set {
                if ((this.MixedField.Equals(value) != true)) {
                    this.MixedField = value;
                    this.RaisePropertyChanged("Mixed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public bool FunBets {
            get {
                return this.FunBetsField;
            }
            set {
                if ((this.FunBetsField.Equals(value) != true)) {
                    this.FunBetsField = value;
                    this.RaisePropertyChanged("FunBets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public bool ManualLogOn {
            get {
                return this.ManualLogOnField;
            }
            set {
                if ((this.ManualLogOnField.Equals(value) != true)) {
                    this.ManualLogOnField = value;
                    this.RaisePropertyChanged("ManualLogOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public bool Parlay {
            get {
                return this.ParlayField;
            }
            set {
                if ((this.ParlayField.Equals(value) != true)) {
                    this.ParlayField = value;
                    this.RaisePropertyChanged("Parlay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public bool Video {
            get {
                return this.VideoField;
            }
            set {
                if ((this.VideoField.Equals(value) != true)) {
                    this.VideoField = value;
                    this.RaisePropertyChanged("Video");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public System.Nullable<int> FundedTimeout {
            get {
                return this.FundedTimeoutField;
            }
            set {
                if ((this.FundedTimeoutField.Equals(value) != true)) {
                    this.FundedTimeoutField = value;
                    this.RaisePropertyChanged("FundedTimeout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public System.Nullable<int> UnfundedTimeout {
            get {
                return this.UnfundedTimeoutField;
            }
            set {
                if ((this.UnfundedTimeoutField.Equals(value) != true)) {
                    this.UnfundedTimeoutField = value;
                    this.RaisePropertyChanged("UnfundedTimeout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public System.Nullable<int> CashReceipts {
            get {
                return this.CashReceiptsField;
            }
            set {
                if ((this.CashReceiptsField.Equals(value) != true)) {
                    this.CashReceiptsField = value;
                    this.RaisePropertyChanged("CashReceipts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public System.Nullable<int> TransactionReceipts {
            get {
                return this.TransactionReceiptsField;
            }
            set {
                if ((this.TransactionReceiptsField.Equals(value) != true)) {
                    this.TransactionReceiptsField = value;
                    this.RaisePropertyChanged("TransactionReceipts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public USRaceList.ConfigurationService.Channels Channels {
            get {
                return this.ChannelsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelsField, value) != true)) {
                    this.ChannelsField = value;
                    this.RaisePropertyChanged("Channels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public USRaceList.ConfigurationService.Languages Languages {
            get {
                return this.LanguagesField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguagesField, value) != true)) {
                    this.LanguagesField = value;
                    this.RaisePropertyChanged("Languages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string BAM {
            get {
                return this.BAMField;
            }
            set {
                if ((object.ReferenceEquals(this.BAMField, value) != true)) {
                    this.BAMField = value;
                    this.RaisePropertyChanged("BAM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public System.Nullable<int> PatronOffset {
            get {
                return this.PatronOffsetField;
            }
            set {
                if ((this.PatronOffsetField.Equals(value) != true)) {
                    this.PatronOffsetField = value;
                    this.RaisePropertyChanged("PatronOffset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public System.Nullable<int> PatronSize {
            get {
                return this.PatronSizeField;
            }
            set {
                if ((this.PatronSizeField.Equals(value) != true)) {
                    this.PatronSizeField = value;
                    this.RaisePropertyChanged("PatronSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public System.Nullable<int> AccountOffset {
            get {
                return this.AccountOffsetField;
            }
            set {
                if ((this.AccountOffsetField.Equals(value) != true)) {
                    this.AccountOffsetField = value;
                    this.RaisePropertyChanged("AccountOffset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public System.Nullable<int> AccountSize {
            get {
                return this.AccountSizeField;
            }
            set {
                if ((this.AccountSizeField.Equals(value) != true)) {
                    this.AccountSizeField = value;
                    this.RaisePropertyChanged("AccountSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public bool Fractional {
            get {
                return this.FractionalField;
            }
            set {
                if ((this.FractionalField.Equals(value) != true)) {
                    this.FractionalField = value;
                    this.RaisePropertyChanged("Fractional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public bool AccountCard {
            get {
                return this.AccountCardField;
            }
            set {
                if ((this.AccountCardField.Equals(value) != true)) {
                    this.AccountCardField = value;
                    this.RaisePropertyChanged("AccountCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public bool Inquiry {
            get {
                return this.InquiryField;
            }
            set {
                if ((this.InquiryField.Equals(value) != true)) {
                    this.InquiryField = value;
                    this.RaisePropertyChanged("Inquiry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public bool ScrambleKeyPad {
            get {
                return this.ScrambleKeyPadField;
            }
            set {
                if ((this.ScrambleKeyPadField.Equals(value) != true)) {
                    this.ScrambleKeyPadField = value;
                    this.RaisePropertyChanged("ScrambleKeyPad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public bool SwipeRequired {
            get {
                return this.SwipeRequiredField;
            }
            set {
                if ((this.SwipeRequiredField.Equals(value) != true)) {
                    this.SwipeRequiredField = value;
                    this.RaisePropertyChanged("SwipeRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public bool Quick {
            get {
                return this.QuickField;
            }
            set {
                if ((this.QuickField.Equals(value) != true)) {
                    this.QuickField = value;
                    this.RaisePropertyChanged("Quick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public System.DateTime CurrentTime {
            get {
                return this.CurrentTimeField;
            }
            set {
                if ((this.CurrentTimeField.Equals(value) != true)) {
                    this.CurrentTimeField = value;
                    this.RaisePropertyChanged("CurrentTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public int DateFormat {
            get {
                return this.DateFormatField;
            }
            set {
                if ((this.DateFormatField.Equals(value) != true)) {
                    this.DateFormatField = value;
                    this.RaisePropertyChanged("DateFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string DatePicture {
            get {
                return this.DatePictureField;
            }
            set {
                if ((object.ReferenceEquals(this.DatePictureField, value) != true)) {
                    this.DatePictureField = value;
                    this.RaisePropertyChanged("DatePicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public bool BrandTime {
            get {
                return this.BrandTimeField;
            }
            set {
                if ((this.BrandTimeField.Equals(value) != true)) {
                    this.BrandTimeField = value;
                    this.RaisePropertyChanged("BrandTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public bool LongTicket {
            get {
                return this.LongTicketField;
            }
            set {
                if ((this.LongTicketField.Equals(value) != true)) {
                    this.LongTicketField = value;
                    this.RaisePropertyChanged("LongTicket");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigurationAccount", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration")]
    [System.SerializableAttribute()]
    public partial class ConfigurationAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.ConfigurationRequired RequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.ConfigurationRequired EditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.ConfigurationRequired ViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CreateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public USRaceList.ConfigurationService.ConfigurationRequired Required {
            get {
                return this.RequiredField;
            }
            set {
                if ((object.ReferenceEquals(this.RequiredField, value) != true)) {
                    this.RequiredField = value;
                    this.RaisePropertyChanged("Required");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public USRaceList.ConfigurationService.ConfigurationRequired Edit {
            get {
                return this.EditField;
            }
            set {
                if ((object.ReferenceEquals(this.EditField, value) != true)) {
                    this.EditField = value;
                    this.RaisePropertyChanged("Edit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public USRaceList.ConfigurationService.ConfigurationRequired View {
            get {
                return this.ViewField;
            }
            set {
                if ((object.ReferenceEquals(this.ViewField, value) != true)) {
                    this.ViewField = value;
                    this.RaisePropertyChanged("View");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public bool Create {
            get {
                return this.CreateField;
            }
            set {
                if ((this.CreateField.Equals(value) != true)) {
                    this.CreateField = value;
                    this.RaisePropertyChanged("Create");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigurationDemand", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration")]
    [System.SerializableAttribute()]
    public partial class ConfigurationDemand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.ConfigurationRequired RequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CreateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public USRaceList.ConfigurationService.ConfigurationRequired Required {
            get {
                return this.RequiredField;
            }
            set {
                if ((object.ReferenceEquals(this.RequiredField, value) != true)) {
                    this.RequiredField = value;
                    this.RaisePropertyChanged("Required");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public bool Create {
            get {
                return this.CreateField;
            }
            set {
                if ((this.CreateField.Equals(value) != true)) {
                    this.CreateField = value;
                    this.RaisePropertyChanged("Create");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigurationContest", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration")]
    [System.SerializableAttribute()]
    public partial class ConfigurationContest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.ConfigurationRequired RequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.ConfigurationRequired EditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.ConfigurationRequired ViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CreateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public USRaceList.ConfigurationService.ConfigurationRequired Required {
            get {
                return this.RequiredField;
            }
            set {
                if ((object.ReferenceEquals(this.RequiredField, value) != true)) {
                    this.RequiredField = value;
                    this.RaisePropertyChanged("Required");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public USRaceList.ConfigurationService.ConfigurationRequired Edit {
            get {
                return this.EditField;
            }
            set {
                if ((object.ReferenceEquals(this.EditField, value) != true)) {
                    this.EditField = value;
                    this.RaisePropertyChanged("Edit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public USRaceList.ConfigurationService.ConfigurationRequired View {
            get {
                return this.ViewField;
            }
            set {
                if ((object.ReferenceEquals(this.ViewField, value) != true)) {
                    this.ViewField = value;
                    this.RaisePropertyChanged("View");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public bool Create {
            get {
                return this.CreateField;
            }
            set {
                if ((this.CreateField.Equals(value) != true)) {
                    this.CreateField = value;
                    this.RaisePropertyChanged("Create");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Advertisement", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration")]
    [System.SerializableAttribute()]
    public partial class Advertisement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisclaimerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Disclaimer {
            get {
                return this.DisclaimerField;
            }
            set {
                if ((object.ReferenceEquals(this.DisclaimerField, value) != true)) {
                    this.DisclaimerField = value;
                    this.RaisePropertyChanged("Disclaimer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Limits", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration")]
    [System.SerializableAttribute()]
    public partial struct Limits : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MaxWagerTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MaxTicketTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MaxDepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MaxWithdrawalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MaxVoucherField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> MaxWagerTotal {
            get {
                return this.MaxWagerTotalField;
            }
            set {
                if ((this.MaxWagerTotalField.Equals(value) != true)) {
                    this.MaxWagerTotalField = value;
                    this.RaisePropertyChanged("MaxWagerTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Nullable<decimal> MaxTicketTotal {
            get {
                return this.MaxTicketTotalField;
            }
            set {
                if ((this.MaxTicketTotalField.Equals(value) != true)) {
                    this.MaxTicketTotalField = value;
                    this.RaisePropertyChanged("MaxTicketTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<decimal> MaxDeposit {
            get {
                return this.MaxDepositField;
            }
            set {
                if ((this.MaxDepositField.Equals(value) != true)) {
                    this.MaxDepositField = value;
                    this.RaisePropertyChanged("MaxDeposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Nullable<decimal> MaxWithdrawal {
            get {
                return this.MaxWithdrawalField;
            }
            set {
                if ((this.MaxWithdrawalField.Equals(value) != true)) {
                    this.MaxWithdrawalField = value;
                    this.RaisePropertyChanged("MaxWithdrawal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Nullable<decimal> MaxVoucher {
            get {
                return this.MaxVoucherField;
            }
            set {
                if ((this.MaxVoucherField.Equals(value) != true)) {
                    this.MaxVoucherField = value;
                    this.RaisePropertyChanged("MaxVoucher");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Currencies", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration", ItemName="Currency")]
    [System.SerializableAttribute()]
    public class Currencies : System.Collections.Generic.List<USRaceList.ConfigurationService.Currency> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SourceMode", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration")]
    public enum SourceMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cash = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Account = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Channels", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration", ItemName="Channel")]
    [System.SerializableAttribute()]
    public class Channels : System.Collections.Generic.List<USRaceList.ConfigurationService.Channel> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Languages", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration", ItemName="Language")]
    [System.SerializableAttribute()]
    public class Languages : System.Collections.Generic.List<USRaceList.ConfigurationService.Language> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Currency", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration")]
    [System.SerializableAttribute()]
    public partial class Currency : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CurrencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DecimalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WagerScaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UnitValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CurrencyId {
            get {
                return this.CurrencyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyIdField, value) != true)) {
                    this.CurrencyIdField = value;
                    this.RaisePropertyChanged("CurrencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<int> Decimals {
            get {
                return this.DecimalsField;
            }
            set {
                if ((this.DecimalsField.Equals(value) != true)) {
                    this.DecimalsField = value;
                    this.RaisePropertyChanged("Decimals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Nullable<int> WagerScale {
            get {
                return this.WagerScaleField;
            }
            set {
                if ((this.WagerScaleField.Equals(value) != true)) {
                    this.WagerScaleField = value;
                    this.RaisePropertyChanged("WagerScale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Period {
            get {
                return this.PeriodField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodField, value) != true)) {
                    this.PeriodField = value;
                    this.RaisePropertyChanged("Period");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Comma {
            get {
                return this.CommaField;
            }
            set {
                if ((object.ReferenceEquals(this.CommaField, value) != true)) {
                    this.CommaField = value;
                    this.RaisePropertyChanged("Comma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public System.Nullable<int> UnitValue {
            get {
                return this.UnitValueField;
            }
            set {
                if ((this.UnitValueField.Equals(value) != true)) {
                    this.UnitValueField = value;
                    this.RaisePropertyChanged("UnitValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Format {
            get {
                return this.FormatField;
            }
            set {
                if ((object.ReferenceEquals(this.FormatField, value) != true)) {
                    this.FormatField = value;
                    this.RaisePropertyChanged("Format");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigurationRequired", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration")]
    [System.SerializableAttribute()]
    public partial class ConfigurationRequired : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExpirationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TaxIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PhraseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PatronField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((this.LastNameField.Equals(value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public bool FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((this.FirstNameField.Equals(value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public bool Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((this.PasswordField.Equals(value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public bool Address {
            get {
                return this.AddressField;
            }
            set {
                if ((this.AddressField.Equals(value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public bool City {
            get {
                return this.CityField;
            }
            set {
                if ((this.CityField.Equals(value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public bool Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((this.ZipField.Equals(value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public bool Country {
            get {
                return this.CountryField;
            }
            set {
                if ((this.CountryField.Equals(value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public bool Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((this.TelephoneField.Equals(value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public bool Area {
            get {
                return this.AreaField;
            }
            set {
                if ((this.AreaField.Equals(value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public bool Email {
            get {
                return this.EmailField;
            }
            set {
                if ((this.EmailField.Equals(value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public bool Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public bool Expiration {
            get {
                return this.ExpirationField;
            }
            set {
                if ((this.ExpirationField.Equals(value) != true)) {
                    this.ExpirationField = value;
                    this.RaisePropertyChanged("Expiration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public bool TaxId {
            get {
                return this.TaxIdField;
            }
            set {
                if ((this.TaxIdField.Equals(value) != true)) {
                    this.TaxIdField = value;
                    this.RaisePropertyChanged("TaxId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public bool DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public bool Phrase {
            get {
                return this.PhraseField;
            }
            set {
                if ((this.PhraseField.Equals(value) != true)) {
                    this.PhraseField = value;
                    this.RaisePropertyChanged("Phrase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public bool Patron {
            get {
                return this.PatronField;
            }
            set {
                if ((this.PatronField.Equals(value) != true)) {
                    this.PatronField = value;
                    this.RaisePropertyChanged("Patron");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Channel", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration")]
    [System.SerializableAttribute()]
    public partial class Channel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MinorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DigitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnalogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BroadcastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Minor {
            get {
                return this.MinorField;
            }
            set {
                if ((object.ReferenceEquals(this.MinorField, value) != true)) {
                    this.MinorField = value;
                    this.RaisePropertyChanged("Minor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public bool Digital {
            get {
                return this.DigitalField;
            }
            set {
                if ((this.DigitalField.Equals(value) != true)) {
                    this.DigitalField = value;
                    this.RaisePropertyChanged("Digital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public bool Analog {
            get {
                return this.AnalogField;
            }
            set {
                if ((this.AnalogField.Equals(value) != true)) {
                    this.AnalogField = value;
                    this.RaisePropertyChanged("Analog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public bool Cable {
            get {
                return this.CableField;
            }
            set {
                if ((this.CableField.Equals(value) != true)) {
                    this.CableField = value;
                    this.RaisePropertyChanged("Cable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public bool Broadcast {
            get {
                return this.BroadcastField;
            }
            set {
                if ((this.BroadcastField.Equals(value) != true)) {
                    this.BroadcastField = value;
                    this.RaisePropertyChanged("Broadcast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration")]
    [System.SerializableAttribute()]
    public partial class Language : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DefaultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public bool Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((this.DefaultField.Equals(value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
    [System.SerializableAttribute()]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private USRaceList.ConfigurationService.ValidationDetail[] DetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public USRaceList.ConfigurationService.ValidationDetail[] Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationDetail", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Practices.EnterpriseLibrary.Val" +
        "idation.Integration.WCF")]
    [System.SerializableAttribute()]
    public partial class ValidationDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag {
            get {
                return this.TagField;
            }
            set {
                if ((object.ReferenceEquals(this.TagField, value) != true)) {
                    this.TagField = value;
                    this.RaisePropertyChanged("Tag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schema.unitedtote.com/ToteLink/2008/06/Configuration", ConfigurationName="ConfigurationService.Configuration")]
    public interface Configuration {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schema.unitedtote.com/ToteLink/2008/06/Common) of message KeepaliveRequest does not match the default value (http://schema.unitedtote.com/ToteLink/2008/06/Configuration)
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.unitedtote.com/ToteLink/2008/06/Common/Keepalive/Keepalive", ReplyAction="http://schema.unitedtote.com/ToteLink/2008/06/Common/Keepalive/KeepaliveResponse")]
        USRaceList.ConfigurationService.KeepaliveResponse Keepalive(USRaceList.ConfigurationService.KeepaliveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.unitedtote.com/ToteLink/2008/06/Common/Keepalive/Keepalive", ReplyAction="http://schema.unitedtote.com/ToteLink/2008/06/Common/Keepalive/KeepaliveResponse")]
        System.Threading.Tasks.Task<USRaceList.ConfigurationService.KeepaliveResponse> KeepaliveAsync(USRaceList.ConfigurationService.KeepaliveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.unitedtote.com/ToteLink/2008/06/Configuration/Configuration/GetConf" +
            "iguration", ReplyAction="http://schema.unitedtote.com/ToteLink/2008/06/Configuration/Configuration/GetConf" +
            "igurationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(USRaceList.ConfigurationService.ValidationFault), Action="http://schema.unitedtote.com/ToteLink/2008/06/Configuration/Configuration/GetConf" +
            "igurationValidationFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConfigurationResponse")]
        USRaceList.ConfigurationService.ConfigurationResponse GetConfiguration(USRaceList.ConfigurationService.ConfigurationRequest ConfigurationRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.unitedtote.com/ToteLink/2008/06/Configuration/Configuration/GetConf" +
            "iguration", ReplyAction="http://schema.unitedtote.com/ToteLink/2008/06/Configuration/Configuration/GetConf" +
            "igurationResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ConfigurationResponse")]
        System.Threading.Tasks.Task<USRaceList.ConfigurationService.ConfigurationResponse> GetConfigurationAsync(USRaceList.ConfigurationService.ConfigurationRequest ConfigurationRequest);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Keepalive", WrapperNamespace="http://schema.unitedtote.com/ToteLink/2008/06/Common", IsWrapped=true)]
    public partial class KeepaliveRequest {
        
        public KeepaliveRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KeepaliveResponse", WrapperNamespace="http://schema.unitedtote.com/ToteLink/2008/06/Common", IsWrapped=true)]
    public partial class KeepaliveResponse {
        
        public KeepaliveResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConfigurationChannel : USRaceList.ConfigurationService.Configuration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigurationClient : System.ServiceModel.ClientBase<USRaceList.ConfigurationService.Configuration>, USRaceList.ConfigurationService.Configuration {
        
        public ConfigurationClient() {
        }
        
        public ConfigurationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigurationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USRaceList.ConfigurationService.KeepaliveResponse USRaceList.ConfigurationService.Configuration.Keepalive(USRaceList.ConfigurationService.KeepaliveRequest request) {
            return base.Channel.Keepalive(request);
        }
        
        public void Keepalive() {
            USRaceList.ConfigurationService.KeepaliveRequest inValue = new USRaceList.ConfigurationService.KeepaliveRequest();
            USRaceList.ConfigurationService.KeepaliveResponse retVal = ((USRaceList.ConfigurationService.Configuration)(this)).Keepalive(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<USRaceList.ConfigurationService.KeepaliveResponse> USRaceList.ConfigurationService.Configuration.KeepaliveAsync(USRaceList.ConfigurationService.KeepaliveRequest request) {
            return base.Channel.KeepaliveAsync(request);
        }
        
        public System.Threading.Tasks.Task<USRaceList.ConfigurationService.KeepaliveResponse> KeepaliveAsync() {
            USRaceList.ConfigurationService.KeepaliveRequest inValue = new USRaceList.ConfigurationService.KeepaliveRequest();
            return ((USRaceList.ConfigurationService.Configuration)(this)).KeepaliveAsync(inValue);
        }
        
        public USRaceList.ConfigurationService.ConfigurationResponse GetConfiguration(USRaceList.ConfigurationService.ConfigurationRequest ConfigurationRequest) {
            return base.Channel.GetConfiguration(ConfigurationRequest);
        }
        
        public System.Threading.Tasks.Task<USRaceList.ConfigurationService.ConfigurationResponse> GetConfigurationAsync(USRaceList.ConfigurationService.ConfigurationRequest ConfigurationRequest) {
            return base.Channel.GetConfigurationAsync(ConfigurationRequest);
        }
    }
}
